version: '3'
services:
  nodejs-app:
    image: node:18 # Usa la imagen oficial de Node.js (versión 18 en este caso)
    container_name: nodejs-websocket-container
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app # Monta el directorio actual al contenedor para tener acceso a los archivos
    ports:
      - "8082:8082" # Mapea el puerto 8080 del contenedor al puerto 8080 del servidor
    command: node server.js # Comando para ejecutar el servidor Node.js
    environment:
      - NODE_ENV=production
    networks:
      - nodejs-network

networks:
  nodejs-network:
    driver: bridge
